version: "3.8"

services:
  web-app:
    build:
      context: .
      dockerfile: web-app/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./web-app/static:/app/static
    depends_on:
      - mongodb
      - machine_learning_client

  test:
    build:
      context: .
      dockerfile: web-app/Dockerfile
    command: pytest tests/test_webapp.py
    depends_on:
      - mongodb
      - machine_learning_client

  ml-test:
    build:
      context: .
      dockerfile: machine_learning_client/Dockerfile
    command: pytest tests/test_mlclient.py
    depends_on:
      - mongodb

  machine_learning_client:
    build:
      context: .
      dockerfile: machine_learning_client/Dockerfile
    volumes:
      - ./web-app/static:/app/static
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
