name: CI-ML-Client

on:
  pull_request:
    branches:
      - main
    paths:
      - 'machine_learning_client/**'
      - 'test/test_mlclient.py'

jobs:
  test-ml-client:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Run ML Client Tests
        run: |
          docker-compose -f docker-compose.yml up --build --abort-on-container-exit ml-test

      - name: Show logs on failure
        if: failure()
        run: docker-compose logs
      
      - name: Install Python dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip
          pip install pylint

      - name: Lint with pylint
        run: |
          pylint machine_learning_client/**/*.py

