name: Web App CI

on:
  pull_request:
    paths:
      - "web-app/**"

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web-app

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest pytest-flask coverage

      - name: Run tests
        run: |
          pytest --cov=app tests/