name: Web App CI

on:
  pull_request:
    paths:
      - "web-app/**"

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web-app

  services:
    mongo:
      image: mongo
      ports:
        - 27017:27017

  steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-flask pytest-cov

      - name: Run tests
        env:
          MONGO_DBNAME: test_db
          MONGO_URI: mongodb://localhost:27017/
          SECRET_KEY: test_secret
        run: |
          pytest --cov=app tests/